// <auto-generated />
namespace prova_nexo_infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class InciandoProjeto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InciandoProjeto));
        
        string IMigrationMetadata.Id
        {
            get { return "202006211756228_InciandoProjeto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
